### ISSUE TITLE
[Bug] Do not Work!!!!!!!

### ISSUE THREAD

**Issue by mVtZWFu** [math0898/OfflinePlayers#6]
The plugin is deactivated with an error
purpur 1.20.1 

i has protocollib and disguise

[11:06:47] [Server thread/INFO]: [WolfyUtilities] Enabled plugin integration for MythicMobs
[11:06:47] [Server thread/INFO]: [OfflinePlayers] Enabling OfflinePlayers v3.1.2
[11:06:47] [Server thread/INFO]: OfflinePlayers starting in version 3.1.2
[11:06:47] [Server thread/ERROR]: Error occurred while enabling OfflinePlayers v3.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/TownyException
	at de.snap20lp.offlineplayers.OfflinePlayers.onEnable(OfflinePlayers.java:71) ~[OfflinePlayers-refresh-optimize-3.3.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.TownyException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
[11:06:47] [Server thread/INFO]: [OfflinePlayers] Disabling OfflinePlayers v3.1.2
[11:06:47] [Server thread/INFO]: [LightCleaner] Enabling LightCleaner v1.19.3-v1
[11:06:47] [Server thread/WARN]: [LightCleaner] minFreeMemory is set to 200MB which is less than recommended (400MB)
[11:06:47] [Server thread/WARN]: [LightCleaner] It is recommended to correct this in the config.yml of Light Cleaner, or risk out of memory errors
[11:06:47] [Server thread/INFO]: [LightCleaner] LightCleaner version 1.19.3-v1 (build: 149) enabled! (0.079s)
[11:06:47] [Server thread/INFO]: [CombatLogX] Enabling CombatLogX v11.4.0.1.1193
[11:06:47] [Server thread/INFO]: [CombatLogX] Successfully loaded 30 language(s).

**Comment by math0898** [comment]
This line tells me that this is a dependency issue.
```
[11:06:47] [Server thread/ERROR]: Error occurred while enabling OfflinePlayers v3.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/TownyException
```
Your server does not have Towny installed. This shouldn't be a problem since #2, #3 and commits 22e3bd830d20912be68db6ff30d359e66b0cdeb1 and 2f857aaa81c51062df2d9dcf6f1636696277c74f.

You'll need to use the latest version if you don't want to add Towny, MultiverseInventories, and DepartedDepot to your server.

I've taken the liberty of building the master branch and posting the binary to a new release. You can find it [here](https://github.com/math0898/OfflinePlayers/releases/tag/v3.3.2).

**Comment by reamianv** [comment]
thank you
